// FIRST LEVEL MENU ITEMS
export const CONTENT_CUSTOMIZER = 'CONTENT_CUSTOMIZER';

// CONTENT CUSTOMIZER MENU ITEMS
export const ONBOARDING_CUSTOMIZE_CONTENT = 'ONBOARDING_CUSTOMIZE_CONTENT';
export const ONBOARDING_SLIDE_CUSTOMIZE_CONTENT = 'ONBOARDING_SLIDE_CUSTOMIZE_CONTENT';

// INSTRUCTION CONTENT
export const INSTRUCTIONS_CONTENT = 'INSTRUCTIONS_CONTENT';
